[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # TMUX
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

[[plugins]] # toml
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  let g:syntastic_rust_checkers = ['rustc']
'''

[[plugins]] # markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
  let g:vim_markdown_folding_disabled = 1
'''
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'mkd']
hook_add = '''
  let g:previm_open_cmd = 'open -a Google\ Chrome'
'''

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'

[[plugins]]
repo = 'mtscout6/syntastic-local-eslint.vim'
on_ft = 'javascript'
hook_add = '''
'''

[[plugins]]
repo = 'kballard/vim-swift'
on_ft = 'swift'

[[plugins]]
repo = 'keith/swift.vim'
on_ft = 'swift'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'
on_i = 1

[[plugins]]
repo = 'enomsg/vim-haskellConcealPlus'
on_ft = 'haskell'

[[plugins]]
repo = 'Twinside/vim-hoogle'
on_ft = 'haskell'
on_i = 1

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = 'haskell'
hook_add = '''
  let g:necoghc_use_stack = 1
'''
